### ISSUE TITLE
android studio import error

### ISSUE THREAD

**Issue by kimmoda** [highjump0615/Skilled_Android#2]
when ı this project android studio import ı get this error : 

Error:Dependency Skilled1:segmentedradios:unspecified on project skilled resolves to an APK archive which is not supported as a compilation dependency. File: C:\Skilled1\segmentedradios\build\outputs\apk\segmentedradios-release-unsigned.apk

**Comment by highjump0615** [comment]
Sorry, this project source code made quite a bit time ago, in 2014, so not using gradle for building project.
I will update project this evening, to support current Android Studio version. :)

**Comment by kimmoda** [comment]
you mean this project working on old android studio version ?

**Comment by highjump0615** [comment]
Yes, when I develop this project, Android Studio version was 0.8~0.9, I guess.
And not used gradle mode when setting up project.
So need some adjustment to support gradle now.

**Comment by kimmoda** [comment]
okay ,thanks for informations.

**Comment by kimmoda** [comment]
ı will wait updating this project .

**Comment by highjump0615** [comment]
I imported the project in Android Studio with grade. Commit done.
